<?php

namespace Sealsix\UserBundle\Entity;

use Symfony\Component\Security\Core\User\UserProviderInterface;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Component\Security\Core\Exception\UnsupportedUserException;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends \Doctrine\ORM\EntityRepository implements UserProviderInterface
{
	public function loadUserByUsername($username){
		$keyRepo = $this->getEntityManager()->getRepository("SealsixUserBundle:APIKey");
		$key = $keyRepo->findOneByHash($username);
		if(!$key)
			return null;
		return $key->getUser();
	}

	public function refreshUser(UserInterface $user){
		throw new UnsupportedUserException();
	}

	public function supportsClass($class){
		return 'Sealsix\UserBundle\Entity\User' === $class;
	}

	public function getUsernameForApiKey($apikey){
		
	}
}
