sealsix_media:
    resource: "@SealsixMediaBundle/Resources/config/routing.yml"
    prefix:   /media

sealsix_user:
    resource: "@SealsixUserBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation

rest:
    type: rest
    resource: "routing_rest.yml"
    prefix: /api