# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
    api_key_user_provider:
        class: Sealsix\UserBundle\Entity\UserRepository
    api_key_authenticator:
        class: Sealsix\UserBundle\Security\ApiKeyAuthenticator
        public: false
    wsse.security.authentication.provider:
        class: Sealsix\UserBundle\Security\Authentication\Provider\WsseProvider
        arguments:
            - "" # User Provider
            - "%kernel.cache_dir%/security/nonces"
        public: false
    wsse.security.authentication.listener:
        class: Sealsix\UserBundle\Security\Firewall\WsseListener
        arguments: ["@security.token_storage", "@security.authentication.manager"]
        public: false