<?php

namespace Sealsix\MediaBundle\Entity;

/**
 * IndexMetaImageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class IndexMetaImageRepository extends \Doctrine\ORM\EntityRepository
{
}
