<?php

namespace Sealsix\MediaBundle\Entity;

/**
 * RankIndexImageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RankIndexVideoRepository extends \Doctrine\ORM\EntityRepository
{
}
